import type {
  BlockSpacingParameters,
  BlockSpacingPreset,
  BlockStyleContract,
  BoxInsets,
  HeaderFooterPresetDefinition,
  MarginPresetDefinition,
  PageSizeDefinition,
  PaginationBehavior,
  StyleSettings,
  TemplateDefinition,
  ThemeDefinition,
  ThemeLayoutMetrics,
  ThemeVisualTokens,
} from './types';
import { DEFAULT_PAGINATION_ALGORITHM_ID } from '@/engine/typesetting/algorithmIds';
import { DEFAULT_CODE_CHAR_WIDTH_FACTOR } from '@/engine/typesetting/textMetrics';

export const pageSizeDefinitions: PageSizeDefinition[] = [
  { id: 'A3', label: 'A3', description: '大幅页面，适合讲义总览和海报草稿', widthMm: 297, heightMm: 420 },
  { id: 'A4', label: 'A4', description: '标准文档尺寸，适合大多数 PDF 讲义', widthMm: 210, heightMm: 297 },
  { id: 'B5', label: 'B5', description: '更紧凑的阅读尺寸，适合笔记与小册子', widthMm: 176, heightMm: 250 },
];

export const marginPresetDefinitions: MarginPresetDefinition[] = [
  {
    id: 'normal',
    label: '普通',
    description: '留白均衡，适合大部分文档',
    valueMm: { top: 22, right: 18, bottom: 22, left: 18 },
  },
  {
    id: 'narrow',
    label: '窄边距',
    description: '尽量扩大正文区域',
    valueMm: { top: 14, right: 12, bottom: 14, left: 12 },
  },
  {
    id: 'wide',
    label: '宽边距',
    description: '增强留白与打印批注空间',
    valueMm: { top: 30, right: 24, bottom: 30, left: 24 },
  },
];

export const headerFooterPresetDefinitions: HeaderFooterPresetDefinition[] = [
  { id: 'none', label: '无', description: '不预留页眉页脚区域', reservedHeightMm: 0 },
  { id: 'compact', label: '紧凑', description: '预留简洁页眉或页脚空间', reservedHeightMm: 10 },
  { id: 'standard', label: '标准', description: '预留常规页眉或页脚空间', reservedHeightMm: 18 },
];

export const templateDefinitions: TemplateDefinition[] = [
  { id: 'default', name: '默认（无模板）', description: '只使用基础解析与页面配置，不叠加额外模板风格' },
  { id: 'lecture', name: '讲义模板', description: '标题层级更强，段落留白更明显，适合课程讲义' },
  { id: 'notes', name: '笔记模板', description: '正文更紧凑，连续阅读效率更高，适合学习笔记' },
];

const defaultThemeTokens: ThemeVisualTokens = {
  pageBackground: '#ffffff',
  pageBorderColor: '#cfd9e3',
  pageShadow: '0 16px 38px rgb(33 45 60 / 14%)',
  pageTopBandColor: 'transparent',
  pagePattern: 'none',
  pagePatternSize: '24px 24px',
  headingFontFamily: 'inherit',
  bodyFontFamily: 'inherit',
  headerBackground: '#ffffff',
  footerBackground: '#ffffff',
  headerFooterText: '#6b7280',
  headerBorderColor: '#edf1f5',
  footerBorderColor: '#edf1f5',
  bodyOutlineColor: '#e4ecf2',
  heading1Color: '#102a43',
  heading1RuleColor: 'transparent',
  heading2Color: '#12314e',
  heading2MarkerColor: 'transparent',
  heading3Color: '#12314e',
  paragraphColor: '#344054',
  mutedTextColor: '#667788',
  listMarkerColor: '#344054',
  taskCheckboxColor: '#0d5663',
  blockquoteBackground: 'transparent',
  blockquoteBorderColor: '#b8d8dc',
  blockquoteTextColor: '#344054',
  codeBackground: '#173047',
  codeBorderColor: 'transparent',
  codeTextColor: '#d7e3f4',
  tableBorderColor: '#d5dde6',
  tableHeaderBackground: '#f3f7fb',
  tableHeaderTextColor: '#213547',
  ruleColor: '#d5dde6',
  pageBreakLineColor: '#b9c7d4',
  pageBreakBackground: '#f4f8fb',
  pageBreakBorderColor: '#d8e1e8',
  pageBreakTextColor: '#506274',
  imageCaptionColor: '#667788',
};

const snowMountainThemeTokens: ThemeVisualTokens = {
  pageBackground: '#FAFDFF',
  pageBorderColor: '#D5E3EB',
  pageShadow: '0 18px 42px rgb(23 50 77 / 12%)',
  pageTopBandColor: '#17324D',
  pagePattern: 'radial-gradient(circle at 12px 12px, rgb(184 212 227 / 0.28) 0.8px, transparent 0.9px)',
  pagePatternSize: '24px 24px',
  headingFontFamily: '"Source Han Serif SC", "Noto Serif SC", "STSong", serif',
  bodyFontFamily: '"Source Han Sans SC", "PingFang SC", "Microsoft YaHei", sans-serif',
  headerBackground: 'rgb(240 247 250 / 92%)',
  footerBackground: 'rgb(240 247 250 / 88%)',
  headerFooterText: '#4E6677',
  headerBorderColor: '#D8E8F0',
  footerBorderColor: '#D8E8F0',
  bodyOutlineColor: '#D7E7EF',
  heading1Color: '#17324D',
  heading1RuleColor: '#F2B84B',
  heading2Color: '#17324D',
  heading2MarkerColor: '#2F6F64',
  heading3Color: '#2F5068',
  paragraphColor: '#24313A',
  mutedTextColor: '#5F7383',
  listMarkerColor: '#2F6F64',
  taskCheckboxColor: '#2F6F64',
  blockquoteBackground: '#EEF7FB',
  blockquoteBorderColor: '#8FB7C6',
  blockquoteTextColor: '#2F5163',
  codeBackground: '#18354F',
  codeBorderColor: '#355A78',
  codeTextColor: '#EFF7FB',
  tableBorderColor: '#C8DCE7',
  tableHeaderBackground: '#E3F0F5',
  tableHeaderTextColor: '#17324D',
  ruleColor: '#C8DCE7',
  pageBreakLineColor: '#BCD0DC',
  pageBreakBackground: '#F0F7FA',
  pageBreakBorderColor: '#CBDDE6',
  pageBreakTextColor: '#4E6677',
  imageCaptionColor: '#547087',
};

// 手绘主题只使用系统字体栈、CSS 变量和内联 SVG 装饰，避免主题依赖外部字体或素材包。
const handDrawnThemeTokens: ThemeVisualTokens = {
  pageBackground: '#FFFDF4',
  pageBorderColor: '#2F2A24',
  pageShadow: '0 16px 30px rgb(47 42 36 / 16%)',
  pageTopBandColor: '#2F2A24',
  pagePattern:
    'radial-gradient(circle at 8px 10px, rgb(47 42 36 / 0.10) 0.8px, transparent 1px), linear-gradient(0deg, rgb(103 86 58 / 0.08) 1px, transparent 1px)',
  pagePatternSize: '22px 22px, 100% 32px',
  headingFontFamily: '"LXGW WenKai", "Kaiti SC", "KaiTi", "STKaiti", "Microsoft YaHei", sans-serif',
  bodyFontFamily: '"LXGW WenKai", "Kaiti SC", "KaiTi", "STKaiti", "Microsoft YaHei", sans-serif',
  headerBackground: 'rgb(255 249 226 / 88%)',
  footerBackground: 'rgb(255 249 226 / 82%)',
  headerFooterText: '#6B4F2A',
  headerBorderColor: '#6B4F2A',
  footerBorderColor: '#6B4F2A',
  bodyOutlineColor: '#CBB88A',
  heading1Color: '#2F2A24',
  heading1RuleColor: '#D88C45',
  heading2Color: '#3A2E25',
  heading2MarkerColor: '#3B7A57',
  heading3Color: '#65451E',
  paragraphColor: '#2F2A24',
  mutedTextColor: '#7B6A52',
  listMarkerColor: '#3B7A57',
  taskCheckboxColor: '#B75F3C',
  blockquoteBackground: '#FFF6D7',
  blockquoteBorderColor: '#B75F3C',
  blockquoteTextColor: '#4A3526',
  codeBackground: '#2F2A24',
  codeBorderColor: '#D88C45',
  codeTextColor: '#FFF6D7',
  tableBorderColor: '#3A2E25',
  tableHeaderBackground: '#FFE8A8',
  tableHeaderTextColor: '#2F2A24',
  ruleColor: '#B75F3C',
  pageBreakLineColor: '#B75F3C',
  pageBreakBackground: '#FFF3C4',
  pageBreakBorderColor: '#D88C45',
  pageBreakTextColor: '#6B4F2A',
  imageCaptionColor: '#6B4F2A',
};

export const defaultThemeLayoutMetrics: ThemeLayoutMetrics = {
  heading1: {
    paddingBottom: 0,
    underlineHeight: 0,
    underlineGap: 0,
    markerInsetLeft: 0,
    underlineOccupiesFlow: false,
  },
  heading2: {
    paddingBottom: 0,
    underlineHeight: 0,
    underlineGap: 0,
    markerInsetLeft: 0,
    underlineOccupiesFlow: false,
  },
  heading3: {
    paddingBottom: 0,
    underlineHeight: 0,
    underlineGap: 0,
    markerInsetLeft: 0,
    underlineOccupiesFlow: false,
  },
};

const handDrawnThemeLayoutMetrics: ThemeLayoutMetrics = {
  heading1: {
    paddingBottom: 10,
    underlineHeight: 14,
    underlineGap: 0,
    markerInsetLeft: 0,
    underlineOccupiesFlow: false,
  },
  heading2: {
    paddingBottom: 0,
    underlineHeight: 8,
    underlineGap: 2,
    markerInsetLeft: 12,
    underlineOccupiesFlow: true,
  },
  heading3: {
    paddingBottom: 0,
    underlineHeight: 8,
    underlineGap: 2,
    markerInsetLeft: 0,
    underlineOccupiesFlow: true,
  },
};

export const themeDefinitions: ThemeDefinition[] = [
  {
    id: 'default',
    name: '默认主题',
    description: '沿用当前清透文档视觉，适合通用讲义与资料。',
    palette: ['#FFFFFF', '#102A43', '#173047', '#F3F7FB'],
    tokens: defaultThemeTokens,
    layoutMetrics: defaultThemeLayoutMetrics,
  },
  {
    id: 'snowMountain',
    name: '雪山静境',
    description: '冷静雪峰与晨曦点缀，适合研学讲义、自然科学资料和阅读型笔记。',
    palette: ['#FAFDFF', '#17324D', '#2F6F64', '#D8EEF7', '#F2B84B'],
    tokens: snowMountainThemeTokens,
    layoutMetrics: defaultThemeLayoutMetrics,
  },
  {
    id: 'handDrawn',
    name: '手绘札记',
    description: '纸张纹理、墨线边框与手绘标记，适合课堂笔记、草稿讲义和轻松阅读资料。',
    palette: ['#FFFDF4', '#2F2A24', '#D88C45', '#3B7A57', '#B75F3C'],
    tokens: handDrawnThemeTokens,
    layoutMetrics: handDrawnThemeLayoutMetrics,
  },
];

export const defaultPaginationBehavior: PaginationBehavior = {
  keepHeadingWithNext: true,
  avoidBreakInsideCodeBlocks: true,
  avoidBreakInsideTables: true,
  avoidBreakInsideImages: true,
};

export const defaultCustomMarginsMm: BoxInsets = {
  top: 20,
  right: 20,
  bottom: 20,
  left: 20,
};

export const defaultBlockStyles: BlockStyleContract = {
  heading1: {
    fontSize: 30,
    lineHeight: 38,
    insetLeft: 0,
    insetRight: 0,
    marginTop: 0,
    marginBottom: 24,
    keepWithNext: true,
    avoidBreakInside: true,
  },
  heading2: {
    fontSize: 24,
    lineHeight: 32,
    insetLeft: 0,
    insetRight: 0,
    marginTop: 22,
    marginBottom: 14,
    keepWithNext: true,
    avoidBreakInside: true,
  },
  heading3: {
    fontSize: 20,
    lineHeight: 28,
    insetLeft: 0,
    insetRight: 0,
    marginTop: 18,
    marginBottom: 12,
    keepWithNext: true,
    avoidBreakInside: true,
  },
  paragraph: {
    fontSize: 16,
    lineHeight: 28,
    insetLeft: 0,
    insetRight: 0,
    marginTop: 0,
    marginBottom: 16,
    keepWithNext: false,
    avoidBreakInside: false,
  },
  list: {
    fontSize: 16,
    lineHeight: 28,
    insetLeft: 0,
    insetRight: 0,
    marginTop: 0,
    marginBottom: 16,
    keepWithNext: false,
    avoidBreakInside: false,
    indent: 24,
    itemGap: 8,
  },
  blockquote: {
    fontSize: 15,
    lineHeight: 28,
    insetLeft: 0,
    insetRight: 0,
    marginTop: 8,
    marginBottom: 18,
    keepWithNext: false,
    avoidBreakInside: false,
  },
  code: {
    fontSize: 14,
    lineHeight: 24,
    marginTop: 8,
    marginBottom: 18,
    keepWithNext: false,
    avoidBreakInside: true,
    paddingX: 16,
    paddingY: 14,
    // 代码块字符宽度统一从命名常量取值，避免在样式默认值里散落魔法数。
    charWidth: DEFAULT_CODE_CHAR_WIDTH_FACTOR,
  },
  table: {
    marginTop: 8,
    marginBottom: 18,
    keepWithNext: false,
    avoidBreakInside: true,
    rowHeight: 42,
    headerRowHeight: 46,
    cellPaddingX: 12,
    cellPaddingY: 10,
  },
  horizontalRule: {
    marginTop: 18,
    marginBottom: 18,
    keepWithNext: false,
    avoidBreakInside: true,
    strokeWidth: 1,
  },
  image: {
    marginTop: 8,
    marginBottom: 18,
    keepWithNext: false,
    avoidBreakInside: true,
    placeholderHeight: 220,
    maxWidthPercent: 100,
    align: 'center',
    captionGap: 8,
  },
};

export const defaultBlockSpacingParameters: BlockSpacingParameters = {
  heading1SpaceBefore: 0,
  heading1SpaceAfter: 24,
  heading2SpaceBefore: 22,
  heading2SpaceAfter: 14,
  heading3SpaceBefore: 18,
  heading3SpaceAfter: 12,
  paragraphSpaceBefore: 0,
  paragraphSpaceAfter: 16,
  listSpaceBefore: 0,
  listSpaceAfter: 16,
  listItemGap: 8,
  blockquoteSpaceBefore: 8,
  blockquoteSpaceAfter: 18,
  codeSpaceBefore: 8,
  codeSpaceAfter: 18,
  codePaddingX: 16,
  codePaddingY: 14,
  tableSpaceBefore: 8,
  tableSpaceAfter: 18,
  tableCellPaddingX: 12,
  tableCellPaddingY: 10,
  imageSpaceBefore: 8,
  imageSpaceAfter: 18,
  ruleSpaceBefore: 18,
  ruleSpaceAfter: 18,
  textInsetLeft: 0,
  textInsetRight: 0,
};

export const blockSpacingPresetDefinitions: BlockSpacingPreset[] = [
  {
    id: 'balanced',
    name: '均衡',
    description: '沿用当前默认排版，适合大多数讲义与笔记。',
    builtIn: true,
    parameters: defaultBlockSpacingParameters,
  },
  {
    id: 'compact',
    name: '紧凑',
    description: '减少段距和内边距，适合内容较密的复习资料。',
    builtIn: true,
    parameters: {
      heading1SpaceBefore: 0,
      heading1SpaceAfter: 18,
      heading2SpaceBefore: 16,
      heading2SpaceAfter: 10,
      heading3SpaceBefore: 12,
      heading3SpaceAfter: 8,
      paragraphSpaceBefore: 0,
      paragraphSpaceAfter: 10,
      listSpaceBefore: 0,
      listSpaceAfter: 10,
      listItemGap: 4,
      blockquoteSpaceBefore: 6,
      blockquoteSpaceAfter: 12,
      codeSpaceBefore: 6,
      codeSpaceAfter: 12,
      codePaddingX: 12,
      codePaddingY: 10,
      tableSpaceBefore: 6,
      tableSpaceAfter: 12,
      tableCellPaddingX: 8,
      tableCellPaddingY: 6,
      imageSpaceBefore: 6,
      imageSpaceAfter: 12,
      ruleSpaceBefore: 12,
      ruleSpaceAfter: 12,
      textInsetLeft: 0,
      textInsetRight: 0,
    },
  },
  {
    id: 'relaxed',
    name: '舒展',
    description: '增加段距和块内留白，适合阅读版讲义。',
    builtIn: true,
    parameters: {
      heading1SpaceBefore: 0,
      heading1SpaceAfter: 30,
      heading2SpaceBefore: 28,
      heading2SpaceAfter: 18,
      heading3SpaceBefore: 22,
      heading3SpaceAfter: 16,
      paragraphSpaceBefore: 0,
      paragraphSpaceAfter: 22,
      listSpaceBefore: 0,
      listSpaceAfter: 22,
      listItemGap: 10,
      blockquoteSpaceBefore: 12,
      blockquoteSpaceAfter: 24,
      codeSpaceBefore: 12,
      codeSpaceAfter: 24,
      codePaddingX: 20,
      codePaddingY: 18,
      tableSpaceBefore: 12,
      tableSpaceAfter: 24,
      tableCellPaddingX: 14,
      tableCellPaddingY: 12,
      imageSpaceBefore: 12,
      imageSpaceAfter: 24,
      ruleSpaceBefore: 24,
      ruleSpaceAfter: 24,
      textInsetLeft: 0,
      textInsetRight: 0,
    },
  },
];

export const defaultStyleSettings: StyleSettings = {
  pageSize: 'A4',
  orientation: 'portrait',
  marginMode: 'preset',
  marginPreset: 'normal',
  customMarginsMm: defaultCustomMarginsMm,
  isMarginLinked: true,
  headerFooterMode: 'preset',
  templateId: 'default',
  themeId: 'default',
  headerPreset: 'none',
  footerPreset: 'none',
  customHeaderReservedMm: 10,
  customFooterReservedMm: 10,
  pageBackground: {
    mode: 'theme',
    color: '#ffffff',
    imageSrc: '',
    imageFit: 'cover',
  },
  pdfWatermark: {
    enabled: false,
    kind: 'text',
    angleDeg: -28,
    opacityPercent: 18,
    text: {
      content: 'LAYOUT3.0',
      fontSizePx: 42,
    },
    image: {
      imageSrc: '',
      widthPercent: 24,
    },
  },
  headerFooterContent: {
    header: {
      left: '{本页标题}',
      center: '',
      right: '',
    },
    footer: {
      left: '',
      center: '',
      right: '{页码}',
    },
  },
  isHeaderFooterLinked: true,
  columns: {
    count: 1,
    gapMm: 8,
    divider: false,
    headingsSpanAll: false,
  },
  paginationAlgorithmId: DEFAULT_PAGINATION_ALGORITHM_ID,
  paginationBehavior: defaultPaginationBehavior,
  blockSpacingPresetId: 'balanced',
  blockSpacing: defaultBlockSpacingParameters,
  customBlockSpacingPresets: [],
};
